// Code generated by jtd-codegen for TypeScript v0.2.1

export interface UserPreferencesV1 {
  defaultDbOptions: DbOptions
}

export enum DbOptionsCaseStyle {
  Camel = 'camel',
  Snake = 'snake',
}

export enum DbOptionsNounForm {
  Plural = 'plural',
  Singular = 'singular',
}

export enum DbOptionsSqlDialect {
  Mariadb = 'mariadb',
  Mssql = 'mssql',
  Mysql = 'mysql',
  Postgres = 'postgres',
  Sqlite = 'sqlite',
}

export interface DbOptions {
  caseStyle: DbOptionsCaseStyle
  migrations: boolean
  nounForm: DbOptionsNounForm
  prefixPks: boolean | null
  sqlDialect: DbOptionsSqlDialect
  timestamps: boolean
}
