import sakilaSchema, { Id as SakilId } from '@src/api/schema/examples/sakila'
import { SqlDialect } from '@src/core/database'
import { ExpectedSchemaCase } from '../cases'

const softDeleteModelIds: string[] = [
  SakilId.Actor,
  SakilId.Customer,
  SakilId.Film,
  SakilId.Staff,
  SakilId.Store,
]

const schema = {
  ...sakilaSchema,
  models: sakilaSchema.models.map((model) =>
    softDeleteModelIds.includes(model.id)
      ? {
          ...model,
          softDelete: true,
        }
      : model,
  ),
}

const cases: ExpectedSchemaCase = {
  schema,
  tableColumns: {
    snakePlural: {
      SequelizeMeta: ['name'],
      actors: ['created_at', 'deleted_at', 'first_name', 'id', 'last_name', 'updated_at'],
      addresses: [
        'address',
        'address2',
        'city_id',
        'created_at',
        'id',
        'phone',
        'postal_code',
        'updated_at',
      ],
      categories: ['created_at', 'id', 'name', 'updated_at'],
      cities: ['city', 'country_id', 'created_at', 'id', 'updated_at'],
      countries: ['country', 'created_at', 'id', 'updated_at'],
      customers: [
        'active',
        'address_id',
        'created_at',
        'deleted_at',
        'email',
        'first_name',
        'id',
        'last_name',
        'store_id',
        'updated_at',
      ],
      film_actors: ['actor_id', 'created_at', 'film_id', 'id', 'updated_at'],
      film_categories: ['category_id', 'created_at', 'film_id', 'id', 'updated_at'],
      films: [
        'created_at',
        'description',
        'deleted_at',
        'id',
        'language_id',
        'length',
        'original_language_id',
        'rating',
        'release_year',
        'rental_duration',
        'rental_rate',
        ['special_feature', [SqlDialect.Postgres]],
        'title',
        'updated_at',
      ],
      inventories: ['created_at', 'film_id', 'id', 'store_id', 'updated_at'],
      languages: ['created_at', 'id', 'name', 'updated_at'],
      payments: [
        'amount',
        'created_at',
        'customer_id',
        'id',
        'payment_date',
        'rental_id',
        'staff_id',
        'updated_at',
      ],
      rentals: [
        'created_at',
        'customer_id',
        'id',
        'inventory_id',
        'rental_date',
        'return_date',
        'staff_id',
        'updated_at',
      ],
      staffs: [
        'active',
        'address_id',
        'created_at',
        'deleted_at',
        'email',
        'first_name',
        'id',
        'last_name',
        'password',
        'picture',
        'store_id',
        'updated_at',
        'username',
      ],
      stores: ['address_id', 'created_at', 'deleted_at', 'id', 'manager_staff_id', 'updated_at'],
    },
    snakeSingular: {
      SequelizeMeta: ['name'],
      actor: ['created_at', 'deleted_at', 'first_name', 'id', 'last_name', 'updated_at'],
      address: [
        'address',
        'address2',
        'city_id',
        'created_at',
        'id',
        'phone',
        'postal_code',
        'updated_at',
      ],
      category: ['created_at', 'id', 'name', 'updated_at'],
      city: ['city', 'country_id', 'created_at', 'id', 'updated_at'],
      country: ['country', 'created_at', 'id', 'updated_at'],
      customer: [
        'active',
        'address_id',
        'created_at',
        'deleted_at',
        'email',
        'first_name',
        'id',
        'last_name',
        'store_id',
        'updated_at',
      ],
      film_actor: ['actor_id', 'created_at', 'film_id', 'id', 'updated_at'],
      film_category: ['category_id', 'created_at', 'film_id', 'id', 'updated_at'],
      film: [
        'created_at',
        'deleted_at',
        'description',
        'id',
        'language_id',
        'length',
        'original_language_id',
        'rating',
        'release_year',
        'rental_duration',
        'rental_rate',
        ['special_feature', [SqlDialect.Postgres]],
        'title',
        'updated_at',
      ],
      inventory: ['created_at', 'film_id', 'id', 'store_id', 'updated_at'],
      language: ['created_at', 'id', 'name', 'updated_at'],
      payment: [
        'amount',
        'created_at',
        'customer_id',
        'id',
        'payment_date',
        'rental_id',
        'staff_id',
        'updated_at',
      ],
      rental: [
        'created_at',
        'customer_id',
        'id',
        'inventory_id',
        'rental_date',
        'return_date',
        'staff_id',
        'updated_at',
      ],
      staff: [
        'active',
        'address_id',
        'created_at',
        'deleted_at',
        'email',
        'first_name',
        'id',
        'last_name',
        'password',
        'picture',
        'store_id',
        'updated_at',
        'username',
      ],
      store: ['address_id', 'created_at', 'deleted_at', 'id', 'manager_staff_id', 'updated_at'],
    },
    camelPlural: {
      SequelizeMeta: ['name'],
      Actors: ['createdAt', 'deletedAt', 'firstName', 'id', 'lastName', 'updatedAt'],
      Addresses: [
        'address',
        'address2',
        'cityId',
        'createdAt',
        'id',
        'phone',
        'postalCode',
        'updatedAt',
      ],
      Categories: ['createdAt', 'id', 'name', 'updatedAt'],
      Cities: ['city', 'countryId', 'createdAt', 'id', 'updatedAt'],
      Countries: ['country', 'createdAt', 'id', 'updatedAt'],
      Customers: [
        'active',
        'addressId',
        'createdAt',
        'deletedAt',
        'email',
        'firstName',
        'id',
        'lastName',
        'storeId',
        'updatedAt',
      ],
      FilmActors: ['actorId', 'createdAt', 'filmId', 'id', 'updatedAt'],
      FilmCategories: ['categoryId', 'createdAt', 'filmId', 'id', 'updatedAt'],
      Films: [
        'createdAt',
        'deletedAt',
        'description',
        'id',
        'languageId',
        'length',
        'originalLanguageId',
        'rating',
        'releaseYear',
        'rentalDuration',
        'rentalRate',
        ['specialFeature', [SqlDialect.Postgres]],
        'title',
        'updatedAt',
      ],
      Inventories: ['createdAt', 'filmId', 'id', 'storeId', 'updatedAt'],
      Languages: ['createdAt', 'id', 'name', 'updatedAt'],
      Payments: [
        'amount',
        'createdAt',
        'customerId',
        'id',
        'paymentDate',
        'rentalId',
        'staffId',
        'updatedAt',
      ],
      Rentals: [
        'createdAt',
        'customerId',
        'id',
        'inventoryId',
        'rentalDate',
        'returnDate',
        'staffId',
        'updatedAt',
      ],
      Staffs: [
        'active',
        'addressId',
        'createdAt',
        'deletedAt',
        'email',
        'firstName',
        'id',
        'lastName',
        'password',
        'picture',
        'storeId',
        'updatedAt',
        'username',
      ],
      Stores: ['addressId', 'createdAt', 'deletedAt', 'id', 'managerStaffId', 'updatedAt'],
    },
    camelSingular: {
      SequelizeMeta: ['name'],
      Actor: ['createdAt', 'deletedAt', 'firstName', 'id', 'lastName', 'updatedAt'],
      Address: [
        'address',
        'address2',
        'cityId',
        'createdAt',
        'id',
        'phone',
        'postalCode',
        'updatedAt',
      ],
      Category: ['createdAt', 'id', 'name', 'updatedAt'],
      City: ['city', 'countryId', 'createdAt', 'id', 'updatedAt'],
      Country: ['country', 'createdAt', 'id', 'updatedAt'],
      Customer: [
        'active',
        'addressId',
        'createdAt',
        'deletedAt',
        'email',
        'firstName',
        'id',
        'lastName',
        'storeId',
        'updatedAt',
      ],
      FilmActor: ['actorId', 'createdAt', 'filmId', 'id', 'updatedAt'],
      FilmCategory: ['categoryId', 'createdAt', 'filmId', 'id', 'updatedAt'],
      Film: [
        'createdAt',
        'deletedAt',
        'description',
        'id',
        'languageId',
        'length',
        'originalLanguageId',
        'rating',
        'releaseYear',
        'rentalDuration',
        'rentalRate',
        ['specialFeature', [SqlDialect.Postgres]],
        'title',
        'updatedAt',
      ],
      Inventory: ['createdAt', 'filmId', 'id', 'storeId', 'updatedAt'],
      Language: ['createdAt', 'id', 'name', 'updatedAt'],
      Payment: [
        'amount',
        'createdAt',
        'customerId',
        'id',
        'paymentDate',
        'rentalId',
        'staffId',
        'updatedAt',
      ],
      Rental: [
        'createdAt',
        'customerId',
        'id',
        'inventoryId',
        'rentalDate',
        'returnDate',
        'staffId',
        'updatedAt',
      ],
      Staff: [
        'active',
        'addressId',
        'createdAt',
        'deletedAt',
        'email',
        'firstName',
        'id',
        'lastName',
        'password',
        'picture',
        'storeId',
        'updatedAt',
        'username',
      ],
      Store: ['addressId', 'createdAt', 'deletedAt', 'id', 'managerStaffId', 'updatedAt'],
    },
    noTimestamps: {
      SequelizeMeta: ['name'],
      actors: ['deleted_at', 'first_name', 'id', 'last_name'],
      addresses: ['address', 'address2', 'city_id', 'id', 'phone', 'postal_code'],
      categories: ['id', 'name'],
      cities: ['city', 'country_id', 'id'],
      countries: ['country', 'id'],
      customers: [
        'active',
        'address_id',
        'deleted_at',
        'email',
        'first_name',
        'id',
        'last_name',
        'store_id',
      ],
      film_actors: ['actor_id', 'film_id', 'id'],
      film_categories: ['category_id', 'film_id', 'id'],
      films: [
        'deleted_at',
        'description',
        'id',
        'language_id',
        'length',
        'original_language_id',
        'rating',
        'release_year',
        'rental_duration',
        'rental_rate',
        ['special_feature', [SqlDialect.Postgres]],
        'title',
      ],
      inventories: ['film_id', 'id', 'store_id'],
      languages: ['id', 'name'],
      payments: ['amount', 'customer_id', 'id', 'payment_date', 'rental_id', 'staff_id'],
      rentals: ['customer_id', 'id', 'inventory_id', 'rental_date', 'return_date', 'staff_id'],
      staffs: [
        'active',
        'address_id',
        'deleted_at',
        'email',
        'first_name',
        'id',
        'last_name',
        'password',
        'picture',
        'store_id',
        'username',
      ],
      stores: ['address_id', 'deleted_at', 'id', 'manager_staff_id'],
    },
    prefixPks: {
      SequelizeMeta: ['name'],
      actors: ['created_at', 'deleted_at', 'first_name', 'actor_id', 'last_name', 'updated_at'],
      addresses: [
        'address',
        'address2',
        'city_id',
        'created_at',
        'address_id',
        'phone',
        'postal_code',
        'updated_at',
      ],
      categories: ['created_at', 'category_id', 'name', 'updated_at'],
      cities: ['city', 'country_id', 'created_at', 'city_id', 'updated_at'],
      countries: ['country', 'created_at', 'country_id', 'updated_at'],
      customers: [
        'active',
        'address_id',
        'created_at',
        'deleted_at',
        'email',
        'first_name',
        'customer_id',
        'last_name',
        'store_id',
        'updated_at',
      ],
      film_actors: ['actor_id', 'created_at', 'film_id', 'film_actor_id', 'updated_at'],
      film_categories: ['category_id', 'created_at', 'film_id', 'film_category_id', 'updated_at'],
      films: [
        'created_at',
        'deleted_at',
        'description',
        'film_id',
        'language_id',
        'length',
        'original_language_id',
        'rating',
        'release_year',
        'rental_duration',
        'rental_rate',
        ['special_feature', [SqlDialect.Postgres]],
        'title',
        'updated_at',
      ],
      inventories: ['created_at', 'film_id', 'inventory_id', 'store_id', 'updated_at'],
      languages: ['created_at', 'language_id', 'name', 'updated_at'],
      payments: [
        'amount',
        'created_at',
        'customer_id',
        'payment_id',
        'payment_date',
        'rental_id',
        'staff_id',
        'updated_at',
      ],
      rentals: [
        'created_at',
        'customer_id',
        'rental_id',
        'inventory_id',
        'rental_date',
        'return_date',
        'staff_id',
        'updated_at',
      ],
      staffs: [
        'active',
        'address_id',
        'created_at',
        'deleted_at',
        'email',
        'first_name',
        'staff_id',
        'last_name',
        'password',
        'picture',
        'store_id',
        'updated_at',
        'username',
      ],
      stores: [
        'address_id',
        'created_at',
        'deleted_at',
        'store_id',
        'manager_staff_id',
        'updated_at',
      ],
    },
  },
}

export default cases
