import studentInfoSystemSchema from '@src/api/schema/examples/studentInfoSystem'
import { ExpectedSchemaCase } from '../cases'

const cases: ExpectedSchemaCase = {
  schema: studentInfoSystemSchema,
  tableColumns: {
    snakePlural: {
      SequelizeMeta: ['name'],
      students: ['birthdate', 'created_at', 'first_name', 'id', 'last_name', 'updated_at'],
      teachers: ['created_at', 'email', 'first_name', 'id', 'last_name', 'updated_at'],
      courses: ['code', 'created_at', 'id', 'name', 'updated_at'],
      course_sections: [
        'course_id',
        'created_at',
        'ends_at',
        'id',
        'number',
        'starts_at',
        'updated_at',
      ],
      course_section_enrollments: [
        'course_section_id',
        'created_at',
        'id',
        'student_id',
        'updated_at',
      ],
      course_section_positions: [
        'course_section_id',
        'created_at',
        'id',
        'teacher_id',
        'updated_at',
      ],
      topics: ['created_at', 'id', 'name', 'updated_at'],
      course_topics: ['course_id', 'topic_id'],
    },
    snakeSingular: {
      SequelizeMeta: ['name'],
      student: ['birthdate', 'created_at', 'first_name', 'id', 'last_name', 'updated_at'],
      teacher: ['created_at', 'email', 'first_name', 'id', 'last_name', 'updated_at'],
      course: ['code', 'created_at', 'id', 'name', 'updated_at'],
      course_section: [
        'course_id',
        'created_at',
        'ends_at',
        'id',
        'number',
        'starts_at',
        'updated_at',
      ],
      course_section_enrollment: [
        'course_section_id',
        'created_at',
        'id',
        'student_id',
        'updated_at',
      ],
      course_section_position: [
        'course_section_id',
        'created_at',
        'id',
        'teacher_id',
        'updated_at',
      ],
      topic: ['created_at', 'id', 'name', 'updated_at'],
      course_topic: ['course_id', 'topic_id'],
    },
    camelPlural: {
      SequelizeMeta: ['name'],
      Students: ['birthdate', 'createdAt', 'firstName', 'id', 'lastName', 'updatedAt'],
      Teachers: ['createdAt', 'email', 'firstName', 'id', 'lastName', 'updatedAt'],
      Courses: ['code', 'createdAt', 'id', 'name', 'updatedAt'],
      CourseSections: ['courseId', 'createdAt', 'endsAt', 'id', 'number', 'startsAt', 'updatedAt'],
      CourseSectionEnrollments: ['courseSectionId', 'createdAt', 'id', 'studentId', 'updatedAt'],
      CourseSectionPositions: ['courseSectionId', 'createdAt', 'id', 'teacherId', 'updatedAt'],
      Topics: ['createdAt', 'id', 'name', 'updatedAt'],
      CourseTopics: ['courseId', 'topicId'],
    },
    camelSingular: {
      SequelizeMeta: ['name'],
      Student: ['birthdate', 'createdAt', 'firstName', 'id', 'lastName', 'updatedAt'],
      Teacher: ['createdAt', 'email', 'firstName', 'id', 'lastName', 'updatedAt'],
      Course: ['code', 'createdAt', 'id', 'name', 'updatedAt'],
      CourseSection: ['courseId', 'createdAt', 'endsAt', 'id', 'number', 'startsAt', 'updatedAt'],
      CourseSectionEnrollment: ['courseSectionId', 'createdAt', 'id', 'studentId', 'updatedAt'],
      CourseSectionPosition: ['courseSectionId', 'createdAt', 'id', 'teacherId', 'updatedAt'],
      Topic: ['createdAt', 'id', 'name', 'updatedAt'],
      CourseTopic: ['courseId', 'topicId'],
    },
    noTimestamps: {
      SequelizeMeta: ['name'],
      students: ['birthdate', 'first_name', 'id', 'last_name'],
      teachers: ['email', 'first_name', 'id', 'last_name'],
      courses: ['code', 'id', 'name'],
      course_sections: ['course_id', 'ends_at', 'id', 'number', 'starts_at'],
      course_section_enrollments: ['course_section_id', 'id', 'student_id'],
      course_section_positions: ['course_section_id', 'id', 'teacher_id'],
      topics: ['id', 'name'],
      course_topics: ['course_id', 'topic_id'],
    },
    prefixPks: {
      SequelizeMeta: ['name'],
      students: ['birthdate', 'created_at', 'first_name', 'last_name', 'student_id', 'updated_at'],
      teachers: ['created_at', 'email', 'first_name', 'last_name', 'teacher_id', 'updated_at'],
      courses: ['code', 'course_id', 'created_at', 'name', 'updated_at'],
      course_sections: [
        'course_id',
        'course_section_id',
        'created_at',
        'ends_at',
        'number',
        'starts_at',
        'updated_at',
      ],
      course_section_enrollments: [
        'course_section_enrollment_id',
        'course_section_id',
        'created_at',
        'student_id',
        'updated_at',
      ],
      course_section_positions: [
        'course_section_id',
        'course_section_position_id',
        'created_at',
        'teacher_id',
        'updated_at',
      ],
      topics: ['created_at', 'name', 'topic_id', 'updated_at'],
      course_topics: ['course_id', 'topic_id'],
    },
  },
}

export default cases
