import ExternalLink from '@src/ui/routing/ExternalLink'
import { classnames, margin } from '@src/ui/styles/classnames'
import { list, subtitle, text, title } from '@src/ui/styles/utils'
import React from 'react'
import { EXAMPLE_SCHEMAS_ID, MY_SCHEMAS_ID } from './constants'

export default function About(): React.ReactElement {
  return (
    <>
      <div className={classnames(margin('mb-2'))}>
        <h2 className={title}>About Sequelize UI</h2>
        <p className={classnames(text)}>
          Sequelize UI is an online{' '}
          <ExternalLink href="https://sequelize.org/">Sequelize ORM</ExternalLink> code generator,
          which generates a full Node.js project in{' '}
          <ExternalLink href="https://www.typescriptlang.org/">TypeScript</ExternalLink>. Use the
          schema editor to create your database tables, fields and associations, then preview the
          Sequelize models and migrations in the code viewer before downloading the project as a zip
          file or copying code from individual files.
        </p>

        <p className={classnames(text)}>
          With Sequelize UI, you can also customize your project with the following database
          configurations:
        </p>
        <ul className={classnames(list, margin('mb-2'))}>
          <li>PostgreSQL, MySQL, MariaDB, SQLite or Microsoft SQL Server dialects.</li>
          <li>Singular or plural table names</li>
          <li>
            <code>camelCase</code> or <code>snake_case</code> table and column names.
          </li>
          <li>
            Table name prefixed primary keys or plain <code>id</code> primary keys.
          </li>
          <li>Created/updated timestamps or no timestamps.</li>
          <li>Paranoid models with deleted timestamps.</li>
        </ul>
        <p className={text}>
          Get started quickly by choosing one of the included{' '}
          <ExternalLink href={`#${EXAMPLE_SCHEMAS_ID}`}>example schemas</ExternalLink>, or{' '}
          <ExternalLink href={`#${MY_SCHEMAS_ID}`}>create your own schema</ExternalLink>.
        </p>
      </div>
      <div className={classnames(margin('mb-2'))}>
        <h3 className={subtitle}>Sequelize UI for plain JavaScript</h3>
        <p className={classnames(text)}>
          This site currently only generates TypeScript code; however, the legacy Sequelize UI site
          is still available at{' '}
          <ExternalLink href="https://js.sequelizeui.app">https://js.sequelizeui.app</ExternalLink>{' '}
          if you want to generate code for a plain JavaScript project. This project is not actively
          maintained, but the goal is to eventually update Sequelize UI to support plain JavaScript
          as well.
        </p>
      </div>
      <div className={classnames(margin('mb-2'))}>
        <h3 className={subtitle}>Other Sequelize code generators</h3>
        <p className={classnames(text)}>
          Sequelize UI is the only web-based code generator for Sequelize and is great for
          generating an entire Sequelize TypeScript project from scratch, or for learning how to
          support different database configurations; however, there are a number of other excellent
          Sequelize code generators.
        </p>
        <p className={classnames(text)}>
          <ExternalLink href="https://github.com/sequelize/cli">Sequelize CLI</ExternalLink> is the
          official Sequelize CLI tool. It supports generating new models and migrations in plain
          JavaScript for your Sequelize project, but does not currently support generating
          TypeScript.
        </p>
        <p className={classnames(text)}>
          If you have an existing database and want to generate compatible Sequelize code,{' '}
          <ExternalLink href="https://github.com/sequelize/sequelize-auto">
            Sequelize Auto
          </ExternalLink>{' '}
          is a CLI tool which supports all SQL dialects and generates Sequelize code in plain
          JavaScript, ES6 or TypeScript. Much of the code generated by Sequelize UI was modeled
          after the code generated by Sequelize Auto. Because Sequelize Auto is meant to generate
          code for an existing database, it does not generate any migration files. There is also a
          desktop application,{' '}
          <ExternalLink href="https://github.com/andyforever/sequelizer">Sequelizer</ExternalLink>,
          which is built on top of Sequelize Auto with an easy to use GUI.
        </p>
      </div>
    </>
  )
}
